[package]
name = "pastebin"
version = "0.1.3"
authors = ["Kaczanowski Mateusz <kaczanowski.mateusz@gmail.com>"]
edition = "2018"

[dependencies]
rocket = { version = "0.4.4", features = ["tls"] }
regex = "1"
humantime = "2.1.0"
rocksdb = "0.21.0"
nanoid = "0.3.0"
flatbuffers = "23.5.26"
structopt = "0.3.26"
structopt-derive = "0.4.18"
num_cpus = "1.16"
handlebars = "4.5.0"
tempdir = "0.3.7"
speculate2 = "0.2.0"
chrono = "0.4.31"
timeago = "0.4.2"
serde_json = "1.0.108"
sha2 = "0.10.8"
hmac = "0.12.1"
