services:
  pastebin:
    image: local/pastebin
    build:
      context: .
    container_name: pastebin
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /var/lib/pastebin.db:/pastebin.db
    command: --ui-line-numbers --address 0.0.0.0 --uri ${URI}
